openapi: 3.0.0
info:
  title: Mero Vision API Swagger
  description: Mero Vision API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://api.merovision.com/
    description: server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Admin
  - name: Admin > Auth
  - name: Admin > Faq
  - name: Admin > Blog Categories
  - name: Admin > Blogs
  - name: Website
  - name: Website > FAQ
paths:
  /api/admin/auth/login:
    post:
      tags:
        - Admin > Auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@merovision.com
                password: Admin@123
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/faqs:
    post:
      tags:
        - Admin > Faq
      summary: store faq
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                question: What is Recruzen?
                answer: Recruzen is an HR and IT company management platform.
                order: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Faq
      summary: show all faq
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/faqs/{id}:
    put:
      tags:
        - Admin > Faq
      summary: update faq
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                question: What is Recruzen?
                answer: Recruzen is an HR and IT company management platform.
                order: 1
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Faq
      summary: delete faq
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blog-categories:
    post:
      tags:
        - Admin > Blog Categories
      summary: store blog categories
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Department
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Blog Categories
      summary: show all blog categories
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: search_keyword
          in: query
          schema:
            type: string
          example: Department
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blog-categories/{id}:
    put:
      tags:
        - Admin > Blog Categories
      summary: update blog category
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Technology
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Blog Categories
      summary: delete blog categories
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blogs:
    post:
      tags:
        - Admin > Blogs
      summary: store blog data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: hy3
                content:
                  type: string
                  example: >-
                    Memory: A simple Spring Boot app often needs 256MB to 1GB of
                    RAM just to start, whereas a Go or NestJS app might only
                    need 50MB to 100MB.

                    Startup Time: Spring can take several seconds to "warm up".
                    However, new technologies like Spring Native (using GraalVM)
                    allow it to start in milliseconds, similar to Go.
                blog_image:
                  type: string
                  format: binary
                category_id:
                  type: integer
                  example: '1'
                status:
                  type: string
                  example: published
                is_featured:
                  type: boolean
                  example: 'true'
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Blogs
      summary: Show all blogs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blogs/{id}:
    put:
      tags:
        - Admin > Blogs
      summary: update blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: hy3
                content:
                  type: string
                  example: >-
                    Memory: A simple Spring Boot app often needs 256MB to 1GB of
                    RAM just to start, whereas a Go or NestJS app might only
                    need 50MB to 100MB.

                    Startup Time: Spring can take several seconds to "warm up".
                    However, new technologies like Spring Native (using GraalVM)
                    allow it to start in milliseconds, similar to Go.
                blog_image:
                  type: string
                  format: binary
                category_id:
                  type: integer
                  example: '1'
                status:
                  type: string
                  example: published
                is_featured:
                  type: boolean
                  example: 'true'
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Blogs
      summary: delete blog
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/blogs/{slug}:
    get:
      tags:
        - Admin > Blogs
      summary: show single blog
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /000/api/faqs:
    get:
      tags:
        - Website > FAQ
      summary: show all faq
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
